### ISSUE TITLE
What is index.xml?

### ISSUE THREAD

**Issue by tyeeman** [zupzup/blog-generator#12]
I'm enjoying the generator but just noticed index.xml is very large. I'm making a backup of some my club's newsletters and storing them into one html/md file per blog post. They vary from 1 or 2 MB to 20MB per file. The images are base64 encoded within the file. When I look at the built www folder, my index.xml file is about the same size as all my posts, which is basically doubling the www folder size. Is this normal??

**Comment by zupzup** [comment]
Hey @tyeeman, glad you like the project!

The `index.xml` is essentially all of the posts within one file in XM format for RSS readers.

**Comment by tyeeman** [comment]
Can I turn off that option, I don't use RSS?

**Comment by zupzup** [comment]
Hey, I just pushed a patch to make it optional, there is now a new config option `userss`.

```toml
generator:
    repo: 'https://github.com/zupzup/blog'
    tmp: 'tmp'
    dest: 'www'
    userss: true
```

If you set it to `false`, rss won't be generated.

**Comment by tyeeman** [comment]
Great, much appreciated! I'll give it a try. Should I do a " go get" to refresh all files??

**Comment by zupzup** [comment]
I think a `go get -u` should update everything :thinking:

**Comment by zupzup** [comment]
Hm..strange. I guess you didn't edit any files in these two packages. I'm not sure why this happens.

You could also try to simply remove it and `go get` it again. I never ran into this myself, so I don't really know what to do in this case, sorry. :/

**Comment by tyeeman** [comment]
I did "git reset --hard" then "go get..." and it seems to have worked.

**Comment by tyeeman** [comment]
OK, all is working very well, thanks for this!

**Comment by zupzup** [comment]
Perfect! no worries :relaxed:
