### ISSUE TITLE
canonical URLs might be broken

### ISSUE THREAD

**Issue by itchyny** [zupzup/blog-generator#13]
Hi, I visited your blog article (https://zupzup.org/epoll-with-rust/) which I found so much interesting but I noticed that canonical URL is wrong.

- https://zupzup.org/epoll-with-rust/ -> canonical = `/` (but should be `https://zupzup.org/epoll-with-rust/`)
- https://zupzup.org/about/ -> canonical = `/` (but should be `https://zupzup.org/about/`)
- https://zupzup.org/tags/rust/ -> canonical = `https://www.zupzup.org/rust/index.html` (which is 404, but should be `https://www.zupzup.org/tags/rust/`)

Setting canonical of all the blog articles to the top page is confusing for crawlers.

**Comment by zupzup** [comment]
Hey @itchyny thanks for reporting this!

I fixed it now :+1:
