### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by tyeeman** [zupzup/blog-generator#7]
Just trying this out. Looks very nice. I'm on windows7. Executed the "go get" to get my exe. Copied the "static" folder over to same folder as the blog-generator.exe. Used the same bloggen.yml file as yours except used my forked repo for the content. Then ran the exe and got this error- 
```
Fetching complete.
Generating Site...
        Generating Post: Syntax-Highlighting from a Markdown source in Go using Chroma...
        Generating Post: Scrolling Endpoint with Kotlin and Spring Boot...
        Generating Post: Elasticsearch to Prometheus Exporter in Go...
        Generating Post: Basic AST Traversal in Go...
        Generating Post: Basic AST Manipulation in Go...
        Generating Post: Ethereum Prepaid Transactions with Go...
        Generating Post: Interactions between Smart Contracts with Solidity...
        Generating Post: The Benefits of Uninterrupted, Focused Work...
        Generating Post: Ethereum Light-Client with React Native...
        Generating Post: HTTP File Upload and Download with Go...
2018/10/10 21:08:53 error executing template www\kotlin-scrolling-endpoint\index.html: template: tem
plate.html:212:14: executing "template.html" at <.HighlightCSS>: can't evaluate field HighlightCSS i
n type generator.IndexData
```
When I look at www\kotlin-scrolling-endpoint\index.html I see no .HighlightCSS in the file. The file actually ends with some styling commands. I forked your content site just to see how it works. Can you see what I'm doing wrong?

I'm also not sure how this generator works.  When I enter the blog url into the config file, how is that related to the content, meaning how does the content get uploaded to that blog url? Automatically or manually?

Update - well delete all the above. I had an older exe from months ago, so I updated it and now the site builds fine. So I just upload to anywhere I want then, yes?

Also, just tried setting the blog url to "http://localhost/zupzup/www" and it doesn't work. All links seem to be based on localhost root, like this - "http://localhost/go-markdown-syntax-highlight-chroma/". Is this working correctly?

**Comment by zupzup** [comment]
Hey,

Yes, there was an update for the Highlighting, so that probably broke it.

The uploading is not automatic, the blog-url in the config is just for the sitemap etc.

You can just upload the files from the `www` folder. I upload them to an S3 bucket for example and serve it from there.

If you want to run it locally, you need to serve the files with a webserver - I'm using the `run.sh` script for that on OS X, but any webserver will do (for example, you could serve it with nginx). Then the links should work as well.

**Comment by tyeeman** [comment]
I'm using Uwamp web server and it works good, and I did run it to serve the www folder but like I said the links don't seem to like a sub directory to run from. Am I correct that it won't work from sub directory like "http://localhost/zupzup/www"

**Comment by zupzup** [comment]
yes, you're correct, it needs to be the root on the web-server, as the navigation currently works that way.

Exactly, you need a meta.yml file for every blog post.

There is not a very strong reason for it - I thought it would be cleaner and it's really not a lot of overhead, plus .yml is easy to parse ;)
