### ISSUE TITLE
not enough arguments in call to

### ISSUE THREAD

**Issue by alebeta90** [zupzup/blog-generator#8]
Hi @zupzup ,

thanks for the amazing code, I'm really looking forward to test it and use it :D

I was perform the step

`go get github.com/zupzup/blog-generator`

And I receive the message

 ``` bash
../go/src/github.com/zupzup/blog-generator/generator/generator.go:243:40: not enough arguments in call to "github.com/alecthomas/chroma/formatters/html".WithClasses
	have ()
	want (bool)
../go/src/github.com/zupzup/blog-generator/generator/post.go:168:41: not enough arguments in call to "github.com/alecthomas/chroma/formatters/html".WithClasses
	have ()
	want (bool)
```
❯ go version
go version go1.12.13 linux/amd64

If you could guide me or give me some advice I will appreciated.

All the best

**Comment by zupzup** [comment]
Hey! Glad you like it ☺️ 

I believe this is a version problem with `chroma`. I pushed a new version useing 0.7.0 and which includes the `true` flag. Now it should work.

Thanks for notifying me of this 👍
